/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models.ODSLiabilities

import models.ApiValue
import models.ODSLiabilities.ODSLiabilities.{Alimony, AnnuityPay, BPA, BpaAllowance, CGAtHigherRateRPCI, CGAtLowerRateRPCI, CGOtherGainsAfterLoss, CapAdjustment, CgAnnualExempt, CgAtEntrepreneursRate, CgAtHigherRate, CgAtLowerRate, CgDueEntrepreneursRate, CgDueHigherRate, CgDueLowerRate, CgGainsAfterLosses, CgTotGainsAfterLosses, ChildBenefitCharge, Class2NicAmt, Class4Nic, CommInvTrustRel, DeficiencyRelief, DividendChargeableAddHRate, DividendChargeableHighRate, DividendChargeableLowRate, DividendTaxAddHighRate, DividendTaxHighRate, DividendTaxLowRate, DividendsPartnership, EisRelief, EmployeeClass1NI, EmployeeClass2NI, EmployerNI, EmploymentBenefits, EmploymentExpenses, ExcludedIncome, ForeignCegDedn, FtcrRestricted, GiftAidTaxReduced, GiftsInvCharities, HigherRateCgtRPCI, IncBenefitSuppAllow, IncomeChargeableAddHRate, IncomeChargeableBasicRate, IncomeChargeableHigherRate, IncomeTaxAddHighRate, IncomeTaxBasicRate, IncomeTaxDue, IncomeTaxHigherRate, ItfCegReceivedAfterTax, JobSeekersAllowance, LFIRelief, LowerRateCgtRPCI, MarriageAllceIn, MarriageAllceOut, NRGTGainsAfterLoss, NetAnnuityPaytsTaxDue, NonDomCharge, NonPayableTaxCredits, NotionalTaxCegs, NotlTaxOtherSource, OthStatePenBenefits, OtherPension, PensionLsumTaxDue, PensionLumpSumTaxRate, PensionSavingChargeable, PersonalAllowance, QualDistnRelief, ReliefForFinanceCosts, SavingsChargeableAddHRate, SavingsChargeableHigherRate, SavingsChargeableLowerRate, SavingsChargeableStartRate, SavingsPartnership, SavingsTaxAddHighRate, SavingsTaxHigherRate, SavingsTaxLowerRate, SavingsTaxStartingRate, SeedEisRelief, SocialInvTaxRel, StatePension, StatePensionGross, SumTotForeignTaxRelief, SumTotLifePolicyGains, SumTotLoanRestricted, SumTotLossRestricted, SummaryTotForeignDiv, SummaryTotForeignIncome, SummaryTotForeignSav, SummaryTotShareOptions, SummaryTotTrustEstates, SummaryTotalDedPpr, SummaryTotalEmployment, SummaryTotalOtherIncome, SummaryTotalPartnership, SummaryTotalSchedule, SummaryTotalUkIntDivs, SummaryTotalUkInterest, SummaryTotalUklProperty, SurplusMcaAlimonyRel, TaxCharged, TaxCreditsForDivs, TaxDueAfterAllceRlf, TaxExcluded, TaxOnCegAhr, TaxOnCegBr, TaxOnCegHr, TaxOnCegSr, TaxOnNonExcludedIncome, TaxOnPayScottishIntermediateRate, TaxOnPayScottishStarterRate, TaxOnRedundancyAhr, TaxOnRedundancyBr, TaxOnRedundancyHr, TaxOnRedundancySir, TaxOnRedundancySsr, TaxableCegAhr, TaxableCegBr, TaxableCegHr, TaxableCegSr, TaxablePayScottishIntermediateRate, TaxablePayScottishStarterRate, TaxableRedundancyAhr, TaxableRedundancyBr, TaxableRedundancyHr, TaxableRedundancySir, TaxableRedundancySsr, TopSlicingRelief, TotalTaxCreditRelief, TradeUnionDeathBenefits, VctSharesRelief}

object ODS2021Liabilities {
  val all2021Liabilities: List[ODSLiabilities with ApiValue] =
    List(
      AnnuityPay,
      BPA,
      BpaAllowance,
      CGAtHigherRateRPCI,
      CGAtLowerRateRPCI,
      CGOtherGainsAfterLoss,
      CapAdjustment,
      CgAnnualExempt,
      CgAtEntrepreneursRate,
      CgAtHigherRate,
      CgAtLowerRate,
      CgDueEntrepreneursRate,
      CgDueHigherRate,
      CgDueLowerRate,
      CgGainsAfterLosses,
      CgTotGainsAfterLosses,
      ChildBenefitCharge,
      Class4Nic,
      CommInvTrustRel,
      DeficiencyRelief,
      Alimony,
      DividendChargeableAddHRate,
      DividendChargeableHighRate,
      DividendChargeableLowRate,
      DividendTaxAddHighRate,
      DividendTaxHighRate,
      DividendTaxLowRate,
      EisRelief,
      EmploymentBenefits,
      EmploymentExpenses,
      ExcludedIncome,
      GiftsInvCharities,
      HigherRateCgtRPCI,
      IncBenefitSuppAllow,
      IncomeChargeableAddHRate,
      IncomeChargeableBasicRate,
      IncomeChargeableHigherRate,
      IncomeTaxAddHighRate,
      IncomeTaxBasicRate,
      IncomeTaxDue,
      IncomeTaxHigherRate,
      JobSeekersAllowance,
      LowerRateCgtRPCI,
      MarriageAllceIn,
      MarriageAllceOut,
      NRGTGainsAfterLoss,
      NetAnnuityPaytsTaxDue,
      NonDomCharge,
      NonPayableTaxCredits,
      NotionalTaxCegs,
      NotlTaxOtherSource,
      OthStatePenBenefits,
      OtherPension,
      PensionLsumTaxDue,
      PensionSavingChargeable,
      PersonalAllowance,
      QualDistnRelief,
      ReliefForFinanceCosts,
      SavingsChargeableAddHRate,
      SavingsChargeableHigherRate,
      SavingsChargeableLowerRate,
      SavingsChargeableStartRate,
      SavingsTaxAddHighRate,
      SavingsTaxHigherRate,
      SavingsTaxLowerRate,
      SavingsTaxStartingRate,
      SeedEisRelief,
      SocialInvTaxRel,
      StatePension,
      StatePensionGross,
      SumTotForeignTaxRelief,
      SumTotLifePolicyGains,
      SumTotLoanRestricted,
      SumTotLossRestricted,
      SummaryTotForeignDiv,
      SummaryTotForeignIncome,
      SummaryTotShareOptions,
      SummaryTotTrustEstates,
      SummaryTotalDedPpr,
      SummaryTotalEmployment,
      SummaryTotalOtherIncome,
      SummaryTotalPartnership,
      SummaryTotalSchedule,
      SummaryTotalUkIntDivs,
      SummaryTotalUkInterest,
      SummaryTotalUklProperty,
      SurplusMcaAlimonyRel,
      TaxablePayScottishIntermediateRate,
      TaxablePayScottishStarterRate,
      TaxCharged,
      TaxCreditsForDivs,
      TaxDueAfterAllceRlf,
      TaxExcluded,
      TaxOnPayScottishIntermediateRate,
      TaxOnPayScottishStarterRate,
      TopSlicingRelief,
      TotalTaxCreditRelief,
      TradeUnionDeathBenefits,
      VctSharesRelief,
      EmployeeClass1NI,
      EmployeeClass2NI,
      EmployerNI,
      LFIRelief,
      SavingsPartnership,
      DividendsPartnership,
      TaxOnNonExcludedIncome,
      SummaryTotForeignSav,
      GiftAidTaxReduced,
      ForeignCegDedn,
      ItfCegReceivedAfterTax,
      FtcrRestricted,
      Class2NicAmt,
      TaxableRedundancyHr,
      TaxableCegHr,
      PensionLumpSumTaxRate,
      TaxOnRedundancyHr,
      TaxOnCegHr,
      TaxOnRedundancyBr,
      TaxOnCegBr,
      TaxOnRedundancyAhr,
      TaxOnRedundancySir,
      TaxOnRedundancySsr,
      TaxOnCegAhr,
      TaxableRedundancyBr,
      TaxableCegBr,
      TaxableRedundancyAhr,
      TaxableCegAhr,
      TaxableCegSr,
      TaxOnCegSr,
      TaxableRedundancySsr,
      TaxableRedundancySir
    )

}
